AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CarRentalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: "CarRentalTable"
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: CarRentalApi
  CarRentalApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !GetAtt ApiGateway.RootResourceId
      RestApiId: !Ref ApiGateway
      Integration:
        IntegrationHttpMethod: POST
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'

